name: Ceris Docs
on:
  push:
    branches: [ 'main' ]
    paths: [ 'docs/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - name: Build and deploy docs
        working-directory: ./docs
        run: mkdocs gh-deploy --force --clean --verbose